require_relative "./gecko_api/version"
require_relative "./gecko_api/controller"
require_relative "./gecko_api/market"
require 'pry'
require 'json'
require 'open-uri'
require 'colorize'
require 'terminal-table'
require 'artii'